version: '2'
services:
    scalesprod-app:
        image: scalesprod
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://scalesprod-postgresql:5432/ScalesProd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scalesprod-postgresql:
        extends:
            file: postgresql.yml
            service: scalesprod-postgresql
